# Generated by Django 3.2.13 on 2022-06-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('ability', models.CharField(max_length=256)),
                ('species', models.CharField(max_length=256)),
                ('defense', models.IntegerField()),
            ],
        ),
    ]
